services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env

  redis:
    image: redis:8.0-alpine

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
      args:
        DOMAIN: ${DOMAIN}
        VITE_BACKEND_URL: https://${DOMAIN}/backend
    volumes:
      - certbot:/etc/letsencrypt/
    ports:
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - certbot:/etc/letsencrypt/
    entrypoint: "certbot certonly --standalone --non-interactive --agree-tos -d ${DOMAIN}"
    ports:
      - "80:80"

volumes:
  certbot:
